name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

jobs:
  ####################
  # Linux / macOS
  ####################

  Linux:
    name: ${{ matrix.name }} (${{ matrix.config }}), ${{ matrix.opts }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [Debug, Release]
        opts: [Geogram_Predicates, Geogram_Psm_Predicates, None]
        include:
          - os: ubuntu-latest
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get -o Acquire::Retries=3 install \
          libblas-dev \
          libboost-filesystem-dev \
          libboost-system-dev \
          libboost-thread-dev \
          libglu1-mesa-dev \
          libsuitesparse-dev \
          xorg-dev \
          ccache
          echo 'CACHE_PATH=~/.ccache' >> "$GITHUB_ENV"

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.opts }}-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.opts }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure with Geogram_Predicates
        if: matrix.opts == 'Geogram_Predicates'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=ON \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Configure with Geogram_Psm_Predicates
        if: matrix.opts == 'Geogram_Psm_Predicates'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Configure without Geogram
        if: matrix.opts == 'None'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cd build; make -j2; ccache --show-stats

      - name: Tests
        run: cd build; make -j2; ./FastEnvelope_test #ctest --verbose --output-on-failure

  ####################
  # macOS
  ####################

  MacOS:
    name: ${{ matrix.name }}-${{ matrix.arch }} (${{ matrix.config }}), ${{ matrix.opts }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        config: [Debug, Release]
        opts: [Geogram_Predicates, Geogram_Psm_Predicates, None]
        arch: [x86_64, arm64]
        include:
          - os: macos-latest
            name: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Dependencies
        run: |
          brew install suite-sparse ccache
          echo 'CACHE_PATH=~/Library/Caches/ccache' >> "$GITHUB_ENV"

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.arch }}-${{ matrix.opts }}-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.arch }}-${{ matrix.opts }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure with Geogram_Predicates
        if: matrix.opts == 'Geogram_Predicates'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=ON \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Configure with Geogram_Psm_Predicates
        if: matrix.opts == 'Geogram_Psm_Predicates'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=ON \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Configure without Geogram
        if: matrix.opts == 'None'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF \
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cd build; make -j2; ccache --show-stats

      - name: Tests
        if: matrix.arch == 'x86_64' # no ARM vm on actions yet
        run: cd build; make -j2; ./FastEnvelope_test #ctest --verbose --output-on-failure

  ####################
  # Windows
  ####################

  Windows:
    name: Windows (${{ matrix.config }}), ${{ matrix.opts }}
    runs-on: windows-2019
    env:
      CC: cl.exe
      CXX: cl.exe
      SCCACHE_IDLE_TIMEOUT: "12000"
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        opts: [Geogram_Predicates, Geogram_Psm_Predicates, None]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set env
        run: |
          echo "appdata=$env:LOCALAPPDATA" >> ${env:GITHUB_ENV}

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ${{ env.appdata }}\Mozilla\sccache
          key: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.opts }}-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.config }}-${{ matrix.opts }}-cache

      - name: Prepare sccache
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install sccache --global
          # Scoop modifies the PATH so we make it available for the next steps of the job
          echo "${env:PATH}" >> ${env:GITHUB_PATH}

      - name: Configure and run with Geogram_Predicates
        if: matrix.opts == 'Geogram_Predicates'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -G Ninja ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=ON ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF ^
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} ^
            -B build ^
            -S .
          cd build
          ninja -j1

      - name: Configure and run with Geogram_Psm_Predicates
        if: matrix.opts == 'Geogram_Psm_Predicates'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -G Ninja ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=ON ^
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} ^
            -B build ^
            -S .
          cd build
          ninja -j1

      - name: Configure and run without Geogram
        if: matrix.opts == 'None'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -G Ninja ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PREDICATES=OFF ^
            -DFAST_ENVELOPE_WITH_GEOGRAM_PSM_PREDICATES=OFF ^
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} ^
            -B build ^
            -S .
          cd build
          ninja -j1

      - name: Tests
        run: |
          cd build
          ./FastEnvelope_test
          #ctest --verbose --output-on-failure
